In [1]:
import torch


In [4]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([-0.1377,  0.1537,  0.9371], requires_grad=True)


In [15]:
y=x+2-2
print(y)
z=y*y*2
z=z.mean()
print(z)

tensor([-0.1377,  0.1537,  0.9371], grad_fn=<SubBackward0>)
tensor(0.6139, grad_fn=<MeanBackward0>)


In [18]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x+2
print(y)
z=y*y*2
z=z.mean()
z.backward()
print(x.grad)

tensor([-1.3323, -1.5070,  1.4890], requires_grad=True)
tensor([0.6677, 0.4930, 3.4890], grad_fn=<AddBackward0>)
tensor([0.8902, 0.6573, 4.6520])


In [28]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x+2
print(y)
z=y*y*2
z=z+96
# z=z.mean()
# z.backward()#dz/dx
# print(x.grad)

tensor([-0.0028,  0.4232,  0.5763], requires_grad=True)
tensor([1.9972, 2.4232, 2.5763], grad_fn=<AddBackward0>)


In [29]:
v=torch.randn(3,dtype=torch.float16)
z.backward(v)
print(x.grad)

tensor([ 1.8451, -3.7791,  2.7448])


In [ ]:
# if it is notscalar we have to give vector

In [36]:
x=torch.randn(3,requires_grad=True)
print(x)

# x.required_grad_(False)
#x.detach()
# with torch.no_grad():

tensor([-0.4923, -0.7015,  0.6155], requires_grad=True)


In [32]:
x.requires_grad_(False)
print(x)

tensor([ 0.7425,  0.7294, -1.3427])


In [35]:
y=x.detach()
print(y)

tensor([0.2492, 1.8887, 0.2938])


In [37]:
with torch.no_grad():
    y=x+2
    print(y)

tensor([1.5077, 1.2985, 2.6155])


In [45]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(7):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([12., 12., 12., 12.])
tensor([15., 15., 15., 15.])
tensor([18., 18., 18., 18.])
tensor([21., 21., 21., 21.])


In [46]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(7):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [49]:
# weights=torch.ones(4,requires_grad=True)
# optimizer=torch.optim.SGD(weights,lr=0.01)
# optimizer.step()
# optimizer.zero_grad()

