In [1]:
# import
import torch
import numpy as np

In [8]:
# working with the tensor
x=torch.tensor([1,2,3,4,5,6,7,8,9])
print(x)
print(x.shape)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [14]:
# 1d 2d 3d dimenstion pytorch
x=torch.empty(1)
print(x)
print(x.shape)
#2d
x=torch.empty(2,3)
print(x)
print(x.shape)
x=torch.empty(2,3,3)
print(x)
print(x.shape)


tensor([2.4200e+24])
torch.Size([1])
tensor([[2.4746e+24, 1.4798e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.Size([2, 3])
tensor([[[2.4192e+24, 1.4798e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([2, 3, 3])


In [16]:

x=torch.rand(2,2)
print(x)

tensor([[0.4625, 0.8015],
        [0.3389, 0.1973]])


In [18]:
x=torch.zeros(2,3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [22]:
x=torch.zeros(2,3,dtype=torch.float16)
print(x.dtype)


torch.float16


In [23]:
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [32]:
x=torch.tensor([2.5,0.1])
y=torch.tensor([7,3],dtype=torch.float16)
print(x+y)


tensor([9.5000, 3.1000])


In [33]:
print(torch.add(x,y))

tensor([9.5000, 3.1000])


In [34]:
y.add_(x)

tensor([9.5000, 3.0996], dtype=torch.float16)

In [35]:
x=torch.tensor([2.5,0.1])
y=torch.tensor([7,3],dtype=torch.float16)
print(x-y)


tensor([-4.5000, -2.9000])


In [37]:
z=x*y
print(z)

tensor([17.5000,  0.3000])


In [39]:
# slicing operations
x=torch.rand(5,3)
x

tensor([[0.9456, 0.9023, 0.8994],
        [0.2459, 0.0092, 0.1868],
        [0.7634, 0.1101, 0.8702],
        [0.3553, 0.0086, 0.9570],
        [0.3202, 0.6747, 0.2792]])

In [51]:
print(x[0:,1])

tensor([0.9023, 0.0092, 0.1101, 0.0086, 0.6747])


In [62]:
print(x[:,1:2])

tensor([[0.9023],
        [0.0092],
        [0.1101],
        [0.0086],
        [0.6747]])


In [63]:
print(x[1,1])

tensor(0.0092)


In [65]:
# reshaping a tensor
x=torch.rand(5,3)
print(x)
print(x.view(15))


tensor([[0.4991, 0.1154, 0.0212],
        [0.6379, 0.2481, 0.2360],
        [0.3754, 0.9072, 0.2838],
        [0.9559, 0.5737, 0.9899],
        [0.0721, 0.0720, 0.9205]])
tensor([0.4991, 0.1154, 0.0212, 0.6379, 0.2481, 0.2360, 0.3754, 0.9072, 0.2838,
        0.9559, 0.5737, 0.9899, 0.0721, 0.0720, 0.9205])


In [83]:
# reshaping a tensor
x=torch.rand(9,9)
y=x.view(-1,3)
print(y.size())


torch.Size([27, 3])


In [80]:
print(x.size())

torch.Size([9, 9])


In [88]:
# converting to numpy to tensor
x=torch.rand(1,5)
print(x)
b=x.numpy()
print(type(b))

tensor([[0.2608, 0.7483, 0.2718, 0.8710, 0.8623]])
<class 'numpy.ndarray'>


In [91]:
# converting numpy to tensor
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)
a+=1
print(a)
print(b)
# it will be modified in the gpu

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [98]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5,device=device)
    z=x+y
    print(z)
    z=z.to("cpu")
    b=z.numpy()

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [100]:
x=torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
